### PR TITLE
update to 47.0

### PR DESCRIPTION
**Pull request by chergert**
as it says

### CODE REVIEW

**Comment by A6GibKm** [comment]
I pushed a few commits to fix the build and lints (I hope), I hope you dont mind

**Comment by chergert** [comment]
> I pushed a few commits to fix the build and lints (I hope), I hope you dont mind

Much appreciated

**Comment by A6GibKm** [comment]
aarch64 builds have been failing rather consistently across flathub

**Comment by A6GibKm** [comment]
bot, build

**Pull request merged**
